name: 'Build and Deploy User Microservice to Cloud Run'

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: 'w4153-team-project-437301' 
  REGION: 'us-central1'
  SERVICE: 'users-microservice' 
  DOCKER_REPO: 'w4153-docker-repo'
  WORKLOAD_IDENTITY_PROVIDER: 'projects/942905232759/locations/global/workloadIdentityPools/github-actions-pool-cloudrun/providers/github-actions-oidc'
  DB_HOST: '34.46.34.153'
  DB_USER: 'root'
  DB_PASSWORD: 'dbuserdbuser'
  DB_NAME: 'w4153'
  PORT: '8000'
  SERVICE_ACCOUNT_PREFIX: 'github-action-cloud-user-ms'

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      # Authenticate using Workload Identity Federation
      - name: 'Authenticate to Google Cloud'
        uses: google-github-actions/auth@v2
        id: auth
        with:
          token_format: 'access_token'
          workload_identity_provider: '${{ env.WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ env.SERVICE_ACCOUNT_PREFIX }}@${{ env.PROJECT_ID }}.iam.gserviceaccount.com'

      - name: Docker Auth
        id: docker-auth
        uses: 'docker/login-action@v3'
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'
          registry: '${{ env.REGION }}-docker.pkg.dev'


      - name: Build, tag and push container
        id: build-image
        uses: docker/build-push-action@v3
        with:
          context: ./
          push: true 
          tags: |
            ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.DOCKER_REPO }}/${{ env.SERVICE }}:${{ github.sha }}

      # Deploy to Cloud Run
      - name: 'Deploy to Cloud Run'
        run: |
          gcloud run deploy ${{ env.SERVICE }} \
            --image ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.DOCKER_REPO }}/${{ env.SERVICE }}:${{ github.sha }} \
            --platform managed \
            --allow-unauthenticated \
            --region=${{ env.REGION }} \
            --port=${{ env.PORT }} \
            --set-env-vars="DB_HOST=${{ env.DB_HOST }},DB_USER=${{ env.DB_USER }},DB_PASSWORD=${{ env.DB_PASSWORD }},DB_NAME=${{ env.DB_NAME }}"


      # Show output
      - name: 'Show Deployment URL'
        run: |
          gcloud run services describe ${{ env.SERVICE }} --region=${{ env.REGION }} --format="value(status.url)"
